openapi: 3.0.0
info:
  title: OpenAPI Template
  version: 1.0.0
  description: >-
    This is a template service.
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /helloworld:
    get:
      tags:
        - template
      operationId: helloWorld
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: string